service: python-opencv


custom:
  pythonRequirements:
    layer: true
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.7
    usePipenv: false
    slim: true
    strip: false
    useDownloadCache: true
    useStaticCache: true


provider:
  name: aws
  runtime: python3.7
  profile: null
  stage: ${opt:stage, 'development'}
  region: ap-northeast-1


plugins:
  - serverless-python-requirements


package:
  exclude:
    - '*/**'
    - './*'
  include:
    - opencv.py


functions:
  opencv:
    handler: opencv.handler
    name: ${self:service}-${self:provider.stage}-opencv
    memorySize: 3008
    timeout: 30
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: opencv
          method: post
          cors: true
