service: serverless


provider:
  name: aws
  runtime: nodejs10.x
  profile: null
  stage: ${opt:stage, 'development'}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        Fn::GetAtt:
          - RetryQueue
          - Arn


package:
  exclude:
    - '*/**'
    - './*'
  include:
    - "functions/*/**"


plugins:
  - serverless-offline-sqs
  - serverless-offline


custom:


functions:
  sqsSend:
    name: ${opt:stage, self:provider.stage}-sqsSend
    handler: functions/sqs/create.handler
    environment:
      QUEUE_URL: "http://0.0.0.0:9324"
    events:
      - http:
          path: api/sqs
          method: post
          timoout: 10

  sqsReceive:
    name: ${opt:stage, self:provider.stage}-sqsReceive
    handler: functions/sqs/receive.handler
    events:
      - sqs:
          queueName: ${opt:stage, , self:provider.stage}-retry-queue
          arn:
            Fn::GetAtt:
              - RetryQueue
              - Arn

resources:
  Resources:
    RetryQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${opt:stage, , self:provider.stage}-retry-queue
        # NOTE: 設定の単位は秒
        ReceiveMessageWaitTimeSeconds: 1
        VisibilityTimeout: 10800
        DelaySeconds: 1
        MessageRetentionPeriod: 172800
